---

hamiltonian: runs/complete_4_hamiltonian.yaml

rbm:
  num_hidden: 20

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

metropolis:
  num_steps: 2000
  warm_steps: 1000
  cherry_pick: 1
  bump_size: 3.5

logging:
  stdout_frequency: 100
