---

hamiltonian: "runs/complete_4_vmc/hamiltonian.yaml"

rbm:
  num_hidden: 20
  init_bias_range: 1.0
  init_weight_std: 0.28867513459481287 # sqrt(2 / (4 + 20))

metropolis:
  num_steps: 24000
  warm_steps: 4000
  cherry_pick: 20
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/complete_4_vmc"
  frequency: 1000
  model: true
  samples: true
