---

# RBM parameters
num_visible: 10
num_hidden: 80

# Hamiltonian is given by
#
#   H = - \frac{h}{2} \sum_{j = 1}^d \frac{\partial^2}{\partial \theta_j^2}
#       + \sum_{(j, k) \in E} \beta_{jk} * (1 - 2 * \cos(\theta_j - \theta_k))
#
# In network specifications, edges are specified by the boundary nodes (j, k)
# and interaction strength \beta_jk
#
# The following specification represents the graph:
#
#   0 - 1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9
#
h: 5.0
edges:
- j: 0
  k: 1
  beta: 1.0
- j: 1
  k: 2
  beta: 1.0
- j: 2
  k: 3
  beta: 1.0
- j: 3
  k: 4
  beta: 1.0
- j: 4
  k: 5
  beta: 1.0
- j: 5
  k: 6
  beta: 1.0
- j: 6
  k: 7
  beta: 1.0
- j: 7
  k: 8
  beta: 1.0
- j: 8
  k: 9
  beta: 1.0

# Gradient descent parmeters
num_step: 10000
lr: 1.0e-03

# SR parameters
sr_reg: 1.0e-05

# Metropolis parameters
metropolis_steps: 2000
bump_size: 3.5
warm_steps: 1000

# Output frequency
logger_stdout_frequency: 100
